### ISSUE TITLE
ItemDecoration support for HeaderRecyclerview

### ISSUE THREAD

**Issue by zourb** [Karumi/HeaderRecyclerView#12]
Can you give an example of ItemDecoration for HeaderRecyclerView with header and footer?

**Comment by pedrovgs** [comment]
Do you need any special `ItemDecoration` configuration?

**Comment by zourb** [comment]
@pedrovgs thanks for you reply, in my HeaderRecyclerView, i have a banner for the header,  a GridLayoutManager RecyclerView for the list content, and a load-more for the footer, it includes header, content and footer, i need a kind of ItemDecoration including edge, is there a general ItemDecoration for the HeaderRecyclerView?

**Comment by pedrovgs** [comment]
@zourb you should take a look at this library we developed few months ago: https://github.com/Karumi/Dividers Review this project and if you don't know how to add the ItemDecoration just let me know.

**Comment by zourb** [comment]
@pedrovgs thanks again, i will dive into it.
