### ISSUE TITLE
Header not being added 

### ISSUE THREAD

**Issue by createS0ftware** [Karumi/HeaderRecyclerView#18]
Hi 

I am using your library and it was working fine until i tested the app in a low connectivity situation - low / intermittent signal. 

In this case it does not show the header . 

is this a known issue ? How can i get around it ?

Thanks

**Comment by createS0ftware** [comment]
It's ok i found the issue

**Comment by pedrovgs** [comment]
Hi @createS0ftware thanks for the issue :) There is something wrong with the library?
