### ISSUE TITLE
HeaderRecyclerViewAdapter methods marked as final

### ISSUE THREAD

**Issue by blipinsk** [Karumi/HeaderRecyclerView#3]
Hi guys!

I think it would be cool if you marked `onCreateViewHolder` and `onBindViewHolder` as `final`. To prevent them from being mistakenly (or purely out of habit) extended. It should be clear that methods you want users to use are `onCreateHeaderViewHolder`, `onCreateItemViewHolder`, `onBindHeaderViewHolder` and `onBindItemViewHolder`. And not the other ones.

Great work still!

Thanks

**Comment by blipinsk** [comment]
also `getItemCount`

**Comment by pedrovgs** [comment]
You are right except for the `getItemCount` method. If a library user wants to extend this class to use also a footer and we mark `getItemCount` method as final he is not going to be able to indicate there is a new element in the adapter which is not inside the `items` collection. 

Thanks for the tip @blipinsk! Can you send us a PR adding the `final` modifier to `onCreateViewHolder` and `onBindViewHolder` method?

If you don't have time, please tell me and I'll add that change in the next release :)

**Comment by blipinsk** [comment]
> You are right except for the getItemCount method. If a library user wants to extend this class to use also a footer and we mark getItemCount method as final he is not going to be able to indicate there is a new element in the adapter which is not inside the items collection.

Yep you're totally right.

> Can you send us a PR adding the final modifier to onCreateViewHolder and onBindViewHolder method?

Sure thing, I will do this today :)

**Comment by blipinsk** [comment]
But wait... if you wanna leave the option to use different `View` types outside `items` collection, then making `onCreateViewHolder` and `onBindViewHolder` final doesn't really make sense, does it?

**Comment by pedrovgs** [comment]
Even if you mark `onCreateViewHolder` and `onBindViewHolder` as final the library user is going to be able to use custom types. Take a look to the code:

``` java

  @Override public VH onCreateViewHolder(ViewGroup parent, int viewType) {
    VH viewHolder;
    if (isHeaderType(viewType)) {
      viewHolder = onCreateHeaderViewHolder(parent, viewType);
    } else {
      viewHolder = onCreateItemViewHolder(parent, viewType);
    }
    return viewHolder;
  }

  @Override public void onBindViewHolder(VH holder, int position) {
    if (isHeaderPosition(position)) {
      onBindHeaderViewHolder(holder, position);
    } else {
      onBindItemViewHolder(holder, position);
    }
  }

```

These methods just check if the view type or the position is related to a header. Making these method finals the library clients can override `onCreateItemViewHolder` and  `onBindItemViewHolder` to implement custom bindings.

**Comment by blipinsk** [comment]
Exactly, therefore the user will have to implement custom groups LOGICALLY within Items `GROUP` (not necessarily within `items` `List<T>`).
