### ISSUE TITLE
Removing an item from the list dinamically misplaces the header

### ISSUE THREAD

**Issue by Antpachon** [Karumi/HeaderRecyclerView#8]
Removing an item from the list dinamically misplaces the header

**Comment by pedrovgs** [comment]
Hi @Antpachon can you attach a screenshot to the issue and provide some information related to the bug like the configuration of your adapter and the piece of code where you are removing items dynamically?

**Comment by Antpachon** [comment]
No worries it was my mistake!

**Comment by pedrovgs** [comment]
Ok, thanks!
